---
all:
  vars:
    ansible_user: ubuntu
  children:
    db_nodes:
      hosts:
        db01:
          ansible_host: 192.0.2.11
          private_ip: 192.0.2.11
          site: onprem
        db02:
          ansible_host: 192.0.2.12
          private_ip: 192.0.2.12
          site: cloud_a
        db03:
          ansible_host: 192.0.2.13
          private_ip: 192.0.2.13
          site: cloud_b
    etcd_nodes:
      hosts:
        etcd01:
          ansible_host: 192.0.2.21
          private_ip: 192.0.2.21
          site: onprem
        etcd02:
          ansible_host: 192.0.2.22
          private_ip: 192.0.2.22
          site: cloud_a
        etcd03:
          ansible_host: 192.0.2.23
          private_ip: 192.0.2.23
          site: cloud_b
    proxy_nodes:
      hosts:
        proxy01:
          ansible_host: 192.0.2.31
          private_ip: 192.0.2.31
          site: onprem
